# Generated by Django 3.0.3 on 2020-02-21 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latestSubmit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='最新提交时间'),
        ),
    ]
