# Generated by Django 3.0.3 on 2020-02-21 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='processData',
            new_name='processDate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='uploadData',
            new_name='uploadDate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceData',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoiceDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='开票日期'),
        ),
    ]
